LogosLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from library import views as library
from users import views as users

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
   # path('users/', include(('users.urls', 'users'), namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('book_list/', library.book_list, name='book_list'),
    path('book/<int:pk>/view/', library.book_view, name='book_view'),
    path('magazine_list/', library.magazine_list, name='magazine_list'),
    path('magazine/<int:pk>/view/', library.magazine_view, name='magazine_view'),
    path('movie_list/', library.movie_list, name='movie_list'),
    path('movie/<int:pk>/view/', library.movie_view, name='movie_view'),
    path('', include('library.urls')),
    path('', include('users.urls')),
]

library/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path

app_name = 'library'
urlpatterns = [
    path('book/add/', views.book_add, name='book_add'),
    path('book/<int:pk>/edit/', views.book_edit, name='book_edit'),
    path('book/<int:pk>/delete/', views.book_delete, name='book_delete'),
    path('magazine/add/', views.magazine_add, name='magazine_add'),
    path('magazine/<int:pk>/edit/', views.magazine_edit, name='magazine_edit'),
    path('magazine/<int:pk>/delete/', views.magazine_delete, name='magazine_delete'),
    path('movie/add/', views.movie_add, name='movie_add'),
    path('movie/<int:pk>/edit/', views.movie_edit, name='movie_edit'),
    path('movie/<int:pk>/delete/', views.movie_delete, name='movie_delete'),
]

users/urls.py
from django.urls import path
from .import views
from .views import SignUpView

app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('account/<int:pk>', views.customUser_view, name='account'),
    path('account/<int:pk>/edit/', views.account_edit, name='account_edit'),
]

library/models.py
from django.db import models


class Book(models.Model):
    book_name = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    book_description = models.TextField()
    quantity = models.IntegerField()
    awards = models.TextField()
    isbn = models.IntegerField()


class Magazine(models.Model):
    magazine_name = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    magazine_description = models.TextField()
    quantity = models.IntegerField()
    country = models.CharField(max_length=100)


class Movie(models.Model):
    movie_name = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    series = models.TextField()
    quantity = models.IntegerField()
    movie_description = models.TextField()

library/forms.py
from django import forms
from .models import Book, Movie, Magazine


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('book_name', 'language', 'genre', 'book_description', 'quantity', 'awards', 'isbn')


class MagazineForm(forms.ModelForm):
    class Meta:
        model = Magazine
        fields = ('magazine_name', 'language', 'genre', 'magazine_description', 'quantity', 'country')


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('movie_name', 'language', 'subject', 'series', 'quantity', 'movie_description')

library/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *


def book_list(request):
    book = Book.objects.filter()
    return render(request, 'library/book_list.html',
                  {'books': book})


def book_view(request, pk):
    if pk:
        book = Book.objects.get(pk=pk)
    else:
        book = request.Book
    return render(request, 'library/book_view.html', {'books': book})

@login_required
def book_add(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            books = Book.objects.filter()
            return redirect('book_list')
    else:
        form = BookForm()
    return render(request, 'library/book_add.html', {'form': form})


@login_required
def book_edit(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        # update
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            book = Book.objects.filter()
            return render(request, 'library/book_list.html',
                          {'books': book})
    else:
        # edit
        form = BookForm(instance=book)
    return render(request, 'library/book_edit.html', {'form': form})


@login_required
def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    book.delete()
    return redirect('book_list')


def magazine_list(request):
    magazine = Magazine.objects.filter()
    return render(request, 'library/magazine_list.html',
                  {'magazines': magazine})


def magazine_view(request, pk):
    if pk:
        magazine = Magazine.objects.get(pk=pk)
    else:
        magazine = request.Magazine
    return render(request, 'library/magazine_view.html', {'magazines': magazine})

@login_required
def magazine_add(request):
    if request.method == "POST":
        form = MagazineForm(request.POST)
        if form.is_valid():
            magazine = form.save(commit=False)
            magazine.save()
            return redirect('magazine_list')
    else:
        form = MagazineForm()
    return render(request, 'library/magazine_add.html', {'form': form})


@login_required
def magazine_edit(request, pk):
    magazine = get_object_or_404(Magazine, pk=pk)
    if request.method == "POST":
        # update
        form = MagazineForm(request.POST, instance=magazine)
        if form.is_valid():
            magazine = form.save(commit=False)
            magazine.save()
            magazine = Magazine.objects.filter()
            return render(request, 'library/magazine_list.html',
                          {'magazines': magazine})
    else:
        # edit
        form = MagazineForm(instance=magazine)
    return render(request, 'library/magazine_edit.html', {'form': form})


@login_required
def magazine_delete(request, pk):
    magazine = get_object_or_404(Magazine, pk=pk)
    magazine.delete()
    return redirect('magazine_list')


def movie_list(request):
    movie = Movie.objects.filter()
    return render(request, 'library/movie_list.html',
                  {'movies': movie})


def movie_view(request, pk):
    if pk:
        movie = Movie.objects.get(pk=pk)
    else:
        movie = request.Movie
    return render(request, 'library/movie_view.html', {'movies': movie})

@login_required
def movie_add(request):
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.save()
            return redirect('movie_list')
    else:
        form = MovieForm()
    return render(request, 'library/movie_add.html', {'form': form})


@login_required
def movie_edit(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.method == "POST":
        # update
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.save()
            movie = Movie.objects.filter()
            return render(request, 'library/movie_list.html',
                          {'movies': movie})
    else:
        # edit
        form = MovieForm(instance=movie)
    return render(request, 'library/movie_edit.html', {'form': form})


@login_required
def movie_delete(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    movie.delete()
    return redirect('movie_list')

library/templates/library/book_add.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
    <h1>Add a New Book</h1>
    <form method="POST">{% csrf_token %}
          {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

</html>

library/templates/library/book_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ book.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'book_list' pk=book.book_name %} ">Cancel</a>
    </form>

{% endblock %}

</html>

library/templates/library/book_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
    <div class="listPage">
    <h1>Edit Book</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>

    </div>
{% endblock %}

</html>

library/templates/library/book_view.html
<!DOCTYPE html>
<html lang="en">

   {% extends 'base.html' %}
    {% load static %}
    {% block title %}Book View{% endblock title %}

    {% block content %}
    <div class="row">
        <h2 style="padding-left: 15Px">Books</h2>
    </div>

    <div class="productPage">
        <main>


            <img src="{% static 'images/Book_Icon.png' %}" alt="stock book" width="400" height="400">

            <p><span class="book"> {{ books.book_name }} </span></p>
            <p1>Quantity:  {{ books.quantity }}</p1><br><br>
            <button type="button">Add to Cart</button><br><br><br>
            <ul>
                <li>Language:  </li><p1>{{ books.language }}</p1><br><br>
                <li>Genre:  </li><p1>{{ books.genre }}</p1><br><br>
                <li>Awards:  </li><p1>{{ books.awards }}</p1><br><br>
                <li>ISBN:  </li><p1>{{ books.isbn }}</p1><br><br>
            </ul>

            <p2>Description:</p2><br>
            <p1>{{ books.book_description }}</p1>

        </main>

    </div>



    {% endblock content %}
</html>

library/templates/library/magazine_add.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
    <h1>Add a New Magazine</h1>
    <form method="POST">{% csrf_token %}
          {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

</html>

library/templates/library/magazine_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ magazine.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'magazine_list' pk=magazine.magazine_name %} ">Cancel</a>
    </form>

{% endblock %}

</html>

library/templates/library/magazine_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
    <div class="listPage">
    <h1>Edit Magazine</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>

    </div>
{% endblock %}

</html>

library/templates/library/magazine_list.html
<!DOCTYPE html>
<html lang="en">
    <style>
			td {
				border: 1px solid #000000;
				padding: 5px;
			}
			tr {
				border: 1px solid #000000;
				padding: 5px;
			}
    </style>
    {% extends 'base.html' %}

    {% block title %}Magazine{% endblock title %}

    {% block content %}
    <div class="row">
        <h2 style="padding-left: 15Px">Magazines</h2>
    </div>
    <div class="listPage">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Magazine Name</th>
                <th>Genre</th>
                <th>Quantity</th>
                <th colspan="2">Actions</th>
                {% if user.is_staff %}
                <th colspan="2">Admin Actions</th>
                {%  endif %}

            </tr>
            </thead>
            <tbody>
            {% for magazine in magazines %}
                <tr>
                    <td>{{ magazine.magazine_name }}</td>
                    <td>{{ magazine.genre }}</td>
                    <td>{{ magazine.quantity }}</td>
                    <td><a href="{% url 'magazine_view' pk=magazine.pk %}" >View</a></td>
                    <td><a href="{% url 'magazine_list'  %}" >Add Cart</a></td>
                    {% if user.is_staff %}
                    <td><a href="{% url 'library:magazine_edit' pk=magazine.pk %}">Edit</a></td>
                    <td><a href="{% url 'library:magazine_delete' pk=magazine.pk %}"
                    onclick="return confirm('Are you sure you want to delete?')"
                    >Delete</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if user.is_staff %}
        <div>
            <a href="{% url 'library:magazine_add' %}">Add Magazine</a>
        </div>
        {% endif %}
    </div>



    {% endblock content %}



</html>

library/templates/library/magazine_view.html
<!DOCTYPE html>
<html lang="en">

   {% extends 'base.html' %}
    {% load static %}
    {% block title %}Magazine View{% endblock title %}

    {% block content %}
    <div class="row">
        <h2 style="padding-left: 15Px">Magazines</h2>
    </div>

    <div class="productPage">
        <main>


            <img src="{% static 'images/Magazine Icon.png' %}" alt="stock magazine" width="400" height="400">

            <p><span class="book"> {{ magazines.magazine_name }} </span></p>
            <p1>Quantity:  {{ magazines.quantity }}</p1><br><br>
            <button type="button">Add to Cart</button><br><br><br>
            <ul>
                <li>Language:  </li><p1>{{ magazines.language }}</p1><br><br>
                <li>Genre:  </li><p1>{{ magazines.genre }}</p1><br><br>
                <li>Country:  </li><p1>{{ magazines.country }}</p1><br><br><br><br><br>
            </ul>

            <p2>Description:</p2><br>
            <p1>{{ movies.movie_description }}</p1>

        </main>

    </div>



    {% endblock content %}
</html>

library/templates/library/movie_add.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
    <h1>Add a New Movie</h1>
    <form method="POST">{% csrf_token %}
          {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

</html>

library/templates/library/movie_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ movie.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'movie_list' pk=movie.movie_name %} ">Cancel</a>
    </form>

{% endblock %}

</html>

library/templates/library/movie_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
    <div class="listPage">
    <h1>Edit Movie</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>

    </div>
{% endblock %}

</html>

library/templates/library/movie_list.html
<!DOCTYPE html>
<html lang="en">
    <style>
			td {
				border: 1px solid #000000;
				padding: 5px;
			}
			tr {
				border: 1px solid #000000;
				padding: 5px;
			}
    </style>
    {% extends 'base.html' %}

    {% block title %}Movies{% endblock title %}

    {% block content %}
    <div class="row">
        <h2 style="padding-left: 15Px">Movies</h2>
    </div>
    <div class="listPage">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Movie Name</th>
                <th>Subject</th>
                <th>Series</th>
                <th>Quantity</th>
                <th colspan="2">Actions</th>
                {% if user.is_staff %}
                <th colspan="2">Admin Actions</th>
                {% endif %}

            </tr>
            </thead>
            <tbody>
            {% for movie in movies %}
                <tr>
                    <td>{{ movie.movie_name }}</td>
                    <td>{{ movie.subject }}</td>
                    <td>{{ movie.series }}</td>
                    <td>{{ movie.quantity }}</td>
                    <td><a href="{% url 'movie_view' pk=movie.pk %}" >View</a></td>
                    <td><a href="{% url 'movie_list'  %}" >Add Cart</a></td>
                    {% if user.is_staff %}
                    <td><a href="{% url 'library:movie_edit' pk=movie.pk %}">Edit</a></td>
                    <td><a href="{% url 'library:movie_delete' pk=movie.pk %}"
                    onclick="return confirm('Are you sure you want to delete?')"
                    >Delete</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if user.is_staff %}
        <div>
            <a href="{% url 'library:movie_add' %}">Add Movie</a>
        </div>
        {% endif %}
    </div>



    {% endblock content %}



</html>

library/templates/library/movie_view.html
<!DOCTYPE html>
<html lang="en">

   {% extends 'base.html' %}
    {% load static %}
    {% block title %}Movie View{% endblock title %}

    {% block content %}
    <div class="row">
        <h2 style="padding-left: 15Px">Movies</h2>
    </div>

    <div class="productPage">
        <main>


            <img src="{% static 'images/Movie Icon.png' %}" alt="stock movie" width="400" height="400">

            <p><span class="book"> {{ movies.movie_name }} </span></p>
            <p1>Quantity:  {{ movies.quantity }}</p1><br><br>
            <button type="button">Add to Cart</button><br><br><br>
            <ul>
                <li>Language:  </li><p1>{{ movies.language }}</p1><br><br>
                <li>Subject:  </li><p1>{{ movies.subject }}</p1><br><br>
                <li>Series:  </li><p1>{{ movies.series }}</p1><br><br><br><br><br>
            </ul>

            <p2>Description:</p2><br>
            <p1>{{ movies.movie_description }}</p1>

        </main>

    </div>



    {% endblock content %}
</html>