LogosLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from library import views as library
from users import views as users

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
   # path('users/', include(('users.urls', 'users'), namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('book_list/', library.book_list, name='book_list'),
    path('book/<int:pk>/view/', library.book_view, name='book_view'),
    path('magazine_list/', library.magazine_list, name='magazine_list'),
    path('magazine/<int:pk>/view/', library.magazine_view, name='magazine_view'),
    path('movie_list/', library.movie_list, name='movie_list'),
    path('movie/<int:pk>/view/', library.movie_view, name='movie_view'),
    path('', include('library.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path
from .import views
from .views import SignUpView

app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('account/<int:pk>', views.customUser_view, name='account'),
    path('account/<int:pk>/edit/', views.account_edit, name='account_edit'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <title>{% block title %}{% endblock %}</title>
      <link href="{% static "css/style3.css" %}" rel="stylesheet">
  </head>
  <body>
  {% if user.is_authenticated %}
    <nav class="navigationBar">
        <div class="logo">
            <a href="/"><img id="navBarLogo" src="{% static "images/LogosLibrary.png" %}"></a>
        </div>
        <div class="navigationBarLinks">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/book_list">Books</a></li>
                <li><a href="/magazine_list">Magazines</a></li>
                <li><a href="/movie_list">Movies</a></li>
                <li><a href="{% url 'users:account' pk=user.pk %}"><img id="navBarAccount" src="{% static "images/Account Icon.png" %}"></a></li>
                <li><a href="{% url 'logout' %}">Log Out</a></li>
        </div>
    </nav>
  {% else %}
    <nav class="navigationBar">
        <div class="logo">
            <a href="/"><img id="navBarLogo" src="{% static "images/LogosLibrary.png" %}"></a>
        </div>
        <div class="navigationBarLinks">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/book_list">Books</a></li>
                <li><a href="/magazine_list">Magazines</a></li>
                <li><a href="/movie_list">Movies</a></li>
                <li><a href="{% url 'login' %}" class="btn btn-outline-secondary">Log In</a></li>
                <li><a href="{% url 'users:signup' %}" class="btn btn-primary ml-2">Sign up</a></li>
            </ul>
        </div>
    </nav>
  {% endif %}
    <nav class="searchBar">

    </nav>
    {% block content %}{% endblock %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

    {% block title %}Home{% endblock title %}

    {% block content %}
        <div id="aboutUsDescription" class="aboutUsPage">
            <h1>About Us</h1>
            <p>Logos Library is a public library that delivers e-content to members. Membership is free for users living in
            the United States, and allows you to check out items for 2 weeks at a time. Because Logos Library delivers
            content electronically, items are automatically returned on their due date. This means Logos Library does not
            charge late fees to its members.</p>
        </div>
        <div id="servicesList" class="aboutUsPage">
            <h1>Services</h1>
            <ul id="aboutUsServices">
                <li><a href="{% url 'book_list' %}"><img class="listPicture" src="{% static "images/Book_Icon.png" %}"></a></li>
                <li><a href="{% url 'movie_list' %}"><img class="listPicture" src="{% static "images/Movie Icon.png" %}"></a></li>
                <li><a href="{% url 'magazine_list' %}"><img class="listPicture" src="{% static "images/Magazine Icon.png" %}"></a></li>
            </ul>
        </div>
    {% endblock content %}
</html>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
    initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <name>{% block name %}CMS App{% endblock name %}</name>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="{% url 'home' %}">Client Management System</a>
     {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a href="{% url 'client_new' %}">+ New</a></li>
        </ul>
      {% endif %}

      <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarCollapse" aria-controls="navbarCollapse"
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu"\
              data-toggle="dropdown" aria-haspopup="true" aria-expanded\
              ="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right"
              aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'password_change'
                %}">Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">
                Log Out</a>
              </div>
            </li>
          </ul>
        {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'login' %}" class="btn btn-outline-secondary">
            Log In</a>
            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">
            Sign up</a>
          </form>
        {% endif %}
      </div>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"\ integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-success" type="submit">Sign Up</button>
</form>
{% endblock content %}
</html>