LogosLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from library import views as library
from users import views as users

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
   # path('users/', include(('users.urls', 'users'), namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('book_list/', library.book_list, name='book_list'),
    path('book/<int:pk>/view/', library.book_view, name='book_view'),
    path('magazine_list/', library.magazine_list, name='magazine_list'),
    path('magazine/<int:pk>/view/', library.magazine_view, name='magazine_view'),
    path('movie_list/', library.movie_list, name='movie_list'),
    path('movie/<int:pk>/view/', library.movie_view, name='movie_view'),
    path('', include('library.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path
from .import views
from .views import SignUpView

app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('account/<int:pk>', views.customUser_view, name='account'),
    path('account/<int:pk>/edit/', views.account_edit, name='account_edit'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    department = models.CharField(max_length=50, default=' ', null=True, blank=True)
    employee_cell_phone = models.CharField(max_length=50, default=' ', null=True, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email', 'department', 'employee_cell_phone')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'department', 'employee_cell_phone')

users/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic
from .forms import *
from django.shortcuts import render, get_object_or_404
from .models import CustomUser


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

@login_required
def customUser_view(request, pk):
    customuser = CustomUser.objects.filter(pk=pk)
    return render(request, 'users/account.html', {"CustomUser": customuser})

@login_required
def account_edit(request, pk):
    account = get_object_or_404(CustomUser, pk=pk)
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=account)
        if form.is_valid():
            account = form.save(commit=False)
            account.save()
            accounts = CustomUser.objects.filter(pk=pk)
            return render(request, 'users/account.html', {'accounts': accounts})
    else:
        # print("else")
        form = CustomUserChangeForm(instance=account)
    return render(request, 'users/account_edit.html', {'form': form})


#class customUserView(LoginRequiredMixin, ListView):
#    model = CustomUser
#    template_name = 'account.html'
#    fields = ('username','email','first_name','last_name')

templates/users/account.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'base.html' %}

    {% block title %}Account{% endblock title %}

    {% block content %}

    <h1>This is account.html</h1>
        <table border="1">
            <tr>
                <td>Username</td>
                <td>Email</td>
                <td>First Name</td>
                <td>Last Name</td>
                <td>Department</td>
                <td>Employee Cell Phone</td>
            </tr>
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.department }}</td>
                <td>{{ user.employee_cell_phone }}</td>
                <td><a href="{% url 'users:account_edit' pk=user.pk %}">Edit Account</a></td>
            </tr>
        </table>
    {% endblock content %}
</html>

templates/users/account_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}

{% block content %}
    <h1>Edit</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
    <button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}
</html>